### PR TITLE
Bug fix, release connections

### PR DESCRIPTION
**Pull request by anderjo4**
Multiple requests to Jenkins caused failure without any exception after 2 requests were done. We now release the connection after a response.
Not sure if this solves the problem and not sure if the connection is released if the client throws an exception.

### CODE REVIEW

**Comment by takesson** [comment]
Have you looked at restclient-hc? How does it manage releasing connections?

Why are there only 2 connections available? A default in httpclient?

What do you mean failing without exception? Is it throwing an Error? Or is it hanging waiting for an available connection?

**Comment by takesson** [comment]
I looked at restclient-hc. It does `httpclient.getConnectionManager().shutdown()`, likely not a good approach and not placed in a finally block.

The code added in this PR should be placed within a finally block.

**Comment by anderjo4** [comment]
Moved the release of the connection to a finally block.

**Comment by anderjo4** [comment]
Tested and confirmed working on Permobil demo server.

**Pull request merged**
